apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-mcp-server.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "prometheus-mcp-server.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "prometheus-mcp-server.fullname" . }}
    spec:
      containers:
        - name: mcp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: PROMETHEUS_BASE_URL
              value: {{ .Values.env.PROMETHEUS_BASE_URL | quote }}
          resources: {{- toYaml .Values.resources | nindent 12 }}

